/// Flutter icons MealsIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MealsIcons
///      fonts:
///       - asset: fonts/MealsIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MealsIcons {
  MealsIcons._();

  static const _kFontFam = 'MealsIcons';
  static const _kFontPkg = null;

  static const IconData pasta_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
